services:
  - type: web
    name: exam-vault
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn EMS.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PINATA_API_KEY
        value: your_actual_key_here
      - key: PINATA_SECRET_API_KEY
        value: your_actual_secret_here
    staticPublishPath: static/
