# Generated by Django 2.2.6 on 2025-06-27 00:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0015_finalpapers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(blank=True, max_length=500, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='request',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_keys/'),
        ),
    ]
